#if !defined(AFX_POINT_H__EE94A845_6447_11D2_AF03_00400141862D__INCLUDED_)
#define AFX_POINT_H__EE94A845_6447_11D2_AF03_00400141862D__INCLUDED_

#if _MSC_VER >= 1000
#pragma once
#endif // _MSC_VER >= 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CPoint1 wrapper class

class CPoint1 : public COleDispatchDriver
{
public:
	CPoint1() {}		// Calls COleDispatchDriver default constructor
	CPoint1(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CPoint1(const CPoint1& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
	long GetX();
	void SetX(long nNewValue);
	long GetY();
	void SetY(long nNewValue);
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Developer Studio will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_POINT_H__EE94A845_6447_11D2_AF03_00400141862D__INCLUDED_)
