// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CPoint1 wrapper class

class CPoint1 : public COleDispatchDriver
{
public:
	CPoint1() {}		// Calls COleDispatchDriver default constructor
	CPoint1(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CPoint1(const CPoint1& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
	long GetX();
	void SetX(long nNewValue);
	long GetY();
	void SetY(long nNewValue);
};
