// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


#include "stdafx.h"
#include "disimage.h"

/////////////////////////////////////////////////////////////////////////////
// CDISImage

IMPLEMENT_DYNCREATE(CDISImage, CWnd)

/////////////////////////////////////////////////////////////////////////////
// CDISImage properties

/////////////////////////////////////////////////////////////////////////////
// CDISImage operations

CString CDISImage::GetPicturePath()
{
	CString result;
	InvokeHelper(0x3e8, DISPATCH_PROPERTYGET, VT_BSTR, (void*)&result, NULL);
	return result;
}

void CDISImage::SetPicturePath(LPCTSTR lpszNewValue)
{
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(0x3e8, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 lpszNewValue);
}
